[RWLT-61][master]
anacoxta/aceleracao-react pull request #18
Opened 2020-06-11 18:46 UTC by IsabellaSoares

# Estabilização e padronização da master

## Descrição do PR

Realizadas as devidas correções para estabilização da branch master e para padronização de código de acordo com as diretrizes da issue #11.

## Descrição técnica da solução

- Removi os arquivos `.css` desnecessários após a instalação do `node-sass`
- Padronizei os nomes das classes com _camelCase_

2020-06-13 15:38 UTC, LiaLobo requested changes
Arrasou no PR! Fiz só alguns apontamentos ;)

2020-06-13 15:38 UTC, LiaLobo commented on src/components/CardProduct/index.js
> +export default CardProduct
Isa, só detalhe, mas que estão no nosso acordo. Ficou faltando os ; após os 'import', return, final da função do componente e no export do componente também.

2020-06-13 15:38 UTC, LiaLobo commented on src/components/Logo/index.js
> +export default Logo;
Como ele é só uma linha, pode deixar mais conciso ainda:

const Logo = () => <span className='Logo'>Fashionista</span>;

E deixar o nome da class em minúsculo (:

2020-06-13 17:46 UTC, IsabellaSoares commented on src/components/CardProduct/index.js
> +export default CardProduct
Bem observado, Lia! Obrigada!

2020-06-14 08:11 UTC, brubriele approved these changes
Muito bom, legal a padronização e limpeza do código! 👏🏼

2020-06-14 08:11 UTC, brubriele commented on src/components/CardProduct/CardProduct.js
> -              {/* [componente title description] */}
Boa, acabei esquecendo de remover, obrigada! 🙂

2020-06-14 17:42 UTC, merged