[RWLT-59] [master]
anacoxta/aceleracao-react pull request #7
Opened 2020-05-16 19:58 UTC by IsabellaSoares

# Funcionalidade do campo de busca + Correções nos arquivos de estilo

## Descrição do PR

- Implementa a funcionalidade de busca ao campo de busca estático implementado na pull request #5. 
- Realizadas correções nos arquivos de estilos (padronização e criação de variáveis globais para cores).

## Capturas de Tela

- Busca _desktop_

![desktop](https://user-images.githubusercontent.com/32148199/82129028-42cf6c80-9796-11ea-8dca-e8b176feb6d5.gif)

- Busca _mobile_

![mobile](https://user-images.githubusercontent.com/32148199/82129035-495de400-9796-11ea-93be-15ea08e13a4a.gif)

## Descrição técnica da solução

- Implementada a funcionalidade de busca
- Adicionado ao repositório um arquivo de _mock_ com os produtos que virão da API
- Removidos os comentários dos arquivos _.scss_
- Criadas variáveis globais para as cores da aplicação

2020-05-16 20:58 UTC, LiaLobo commented on src/components/Search/Input/Input.js
> +            <li key={index}>{item.name}</li>
Muito bom o pull request, daora! Só quero tirar uma dúvida nessa linha. Essa key com index foi o que a Yuki comentou hoje que pode dar problema caso o index seja alterado, certo? (ou algo assim, não sei se entendi exatamente o problema) Então não seria melhor colocarmos outro item no lugar do index?

2020-05-16 21:15 UTC, IsabellaSoares commented on src/components/Search/Input/Input.js
> +            <li key={index}>{item.name}</li>
Resolvido, Lia!

2020-05-18 01:32 UTC, brubriele requested changes
@IsabellaSoares muito bacana as funcionalidades implementadas na busca, deixei alguns apontamentos inline.

2020-05-18 01:32 UTC, brubriele commented on src/components/Search/Search.scss
>  @media (max-width: $md) {
- Fiquei em dúvida se seria algum padrão de classNames em React, mas caso não seja, acho que podemos manter o padrão de nomear as classes de estilo separadas por hífen.

- Nesse trecho é possível sintetizar utilizando o & comercial para agrupar as duas classes que compartilham do mesmo elemento:

`@media (max-width: $md) {
  .desktopSearchContainer,
  &__inputSearch {
    display: none;
  }
}`

2020-05-18 01:32 UTC, brubriele commented on src/components/Search/Input/Input.js
> +        product.name.toLowerCase().includes(searchTerm)
Ao testar o filtro, identifiquei que não estava filtrando quando o usuário insere caracteres maiúsculos ou mesclando maiúsculo e minúsculo no termo de busca, acrescentei a seguinte correção à linha:

`product.name.toLowerCase().includes(searchTerm.toLowerCase())`

2020-05-18 13:26 UTC, vanessa-ariel approved these changes

2020-05-18 18:01 UTC, brubriele approved these changes
Finalizado o review @IsabellaSoares , ficou show! ;)

2020-05-18 18:48 UTC, merged